export { default as Home } from './Home'
export { default as Inputanimation } from './Inputanimation'
export { default as Stagger } from './Stagger'
export { default as Grid } from './Grid'
export { default as TimelinePage } from './TimelinePage'